language: node_js
cache:
  directories:
    - node_modules  
after_success:
  echo "Notify traffic light to be green"
  # curl LOCALIP/sucesso
after_failure:
  echo "Notify traffic light to be red"
  # curl LOCALIP/falha
